import type { Produto, Movimentacao } from "~/types/estoque";

export const useMockProdutos = () =>
  useState<Produto[]>("produtos", () => [
    {
      id: "1",
      nome: "Ração Cães Premium",
      categoria: "racao",
      unidade: "kg",
      quantidadeAtual: 8,
      quantidadeMinima: 10,
      precoCusto: 25,
      precoVenda: 40,
      descricao: "Ração seca para cães adultos",
      ativo: true,
    },
    {
      id: "2",
      nome: "Ração Gatos Premium",
      categoria: "racao",
      unidade: "kg",
      quantidadeAtual: 5,
      quantidadeMinima: 8,
      precoCusto: 28,
      precoVenda: 45,
      descricao: "Ração seca para gatos adultos",
      ativo: true,
    },
    {
      id: "3",
      nome: "Shampoo Neutro",
      categoria: "higiene",
      unidade: "un.",
      quantidadeAtual: 12,
      quantidadeMinima: 5,
      precoCusto: 18,
      precoVenda: 35,
      ativo: true,
    },
    {
      id: "4",
      nome: "Condicionador Pet",
      categoria: "higiene",
      unidade: "un.",
      quantidadeAtual: 3,
      quantidadeMinima: 4,
      precoCusto: 20,
      precoVenda: 38,
      ativo: true,
    },
    {
      id: "5",
      nome: "Antipulgas Spot-On",
      categoria: "medicamento",
      unidade: "cx",
      quantidadeAtual: 6,
      quantidadeMinima: 3,
      precoCusto: 45,
      precoVenda: 80,
      descricao: "Tratamento antipulgas mensal",
      ativo: true,
    },
    {
      id: "6",
      nome: "Vermífugo Comprimido",
      categoria: "medicamento",
      unidade: "cx",
      quantidadeAtual: 2,
      quantidadeMinima: 5,
      precoCusto: 30,
      precoVenda: 55,
      ativo: true,
    },
    {
      id: "7",
      nome: "Brinquedo Mordedor",
      categoria: "acessorio",
      unidade: "un.",
      quantidadeAtual: 30,
      quantidadeMinima: 10,
      precoCusto: 12,
      precoVenda: 25,
      ativo: true,
    },
    {
      id: "8",
      nome: "Coleira Ajustável P",
      categoria: "acessorio",
      unidade: "un.",
      quantidadeAtual: 15,
      quantidadeMinima: 5,
      precoCusto: 8,
      precoVenda: 18,
      ativo: true,
    },
  ]);

export const useMockMovimentacoes = () =>
  useState<Movimentacao[]>("movimentacoes", () => [
    {
      id: "1",
      produtoId: "1",
      tipo: "entrada",
      quantidade: 20,
      data: "2026-03-10",
      motivo: "Compra fornecedor",
    },
    {
      id: "2",
      produtoId: "1",
      tipo: "saida",
      quantidade: 12,
      data: "2026-03-15",
      motivo: "Venda",
    },
    {
      id: "3",
      produtoId: "3",
      tipo: "entrada",
      quantidade: 15,
      data: "2026-03-12",
      motivo: "Compra fornecedor",
    },
    {
      id: "4",
      produtoId: "6",
      tipo: "saida",
      quantidade: 3,
      data: "2026-03-18",
      motivo: "Uso em atendimento",
    },
  ]);
