import type { Cliente } from "~/types/cliente";

const MOCK_CLIENTES: Cliente[] = [
  {
    id: "1",
    nome: "João Silva",
    cpf: "123.456.789-00",
    telefonePrincipal: "(11) 99999-0001",
    telefoneSecundario: "",
    email: "joao.silva@email.com",
    cep: "01001-000",
    rua: "Rua das Flores",
    numero: "10",
    complemento: "",
    bairro: "Centro",
    cidade: "São Paulo",
    estado: "SP",
    dataNascimento: "1985-04-12",
    comoConheceu: "Indicação",
    observacoes: "Pet alérgico a frango",
    status: "Ativo",
    createdAt: "2025-01-10T09:00:00",
    pets: [
      {
        id: "p1",
        clienteId: "1",
        nome: "Rex",
        raca: "Labrador",
        especie: "Cão",
        tamanho: "Grande",
        idade: "5 anos",
        peso: "32",
        observacoes: "Alérgico a frango",
        createdAt: "2025-01-10T09:30:00",
      },
    ],
  },
  {
    id: "2",
    nome: "Maria Souza",
    cpf: "234.567.890-11",
    telefonePrincipal: "(21) 98888-0002",
    telefoneSecundario: "",
    email: "maria.souza@email.com",
    cep: "20040-020",
    rua: "Av. Rio Branco",
    numero: "200",
    complemento: "Apto 5",
    bairro: "Centro",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    dataNascimento: "1990-07-23",
    comoConheceu: "Redes sociais",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-01-15T10:30:00",
    pets: [
      {
        id: "p2",
        clienteId: "2",
        nome: "Luna",
        raca: "Persa",
        especie: "Gato",
        tamanho: "Pequeno",
        idade: "3 anos",
        peso: "4",
        observacoes: "",
        createdAt: "2025-01-15T11:00:00",
      },
      {
        id: "p3",
        clienteId: "2",
        nome: "Bella",
        raca: "SRD",
        especie: "Gato",
        tamanho: "Pequeno",
        idade: "1 ano",
        peso: "3.5",
        observacoes: "",
        createdAt: "2025-01-20T14:00:00",
      },
    ],
  },
  {
    id: "3",
    nome: "Carlos Lima",
    cpf: "345.678.901-22",
    telefonePrincipal: "(31) 97777-0003",
    telefoneSecundario: "(31) 96666-0003",
    email: "carlos.lima@email.com",
    cep: "30130-110",
    rua: "Rua da Bahia",
    numero: "55",
    complemento: "",
    bairro: "Lourdes",
    cidade: "Belo Horizonte",
    estado: "MG",
    dataNascimento: "1978-11-05",
    comoConheceu: "Google",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-02-01T08:00:00",
    pets: [],
  },
  {
    id: "4",
    nome: "Pedro Alves",
    cpf: "456.789.012-33",
    telefonePrincipal: "(41) 96666-0004",
    telefoneSecundario: "",
    email: "pedro.alves@email.com",
    cep: "80010-010",
    rua: "Rua XV de Novembro",
    numero: "300",
    complemento: "",
    bairro: "Centro",
    cidade: "Curitiba",
    estado: "PR",
    dataNascimento: "1995-02-18",
    comoConheceu: "Indicação",
    observacoes: "Prefere atendimento pela manhã",
    status: "Ativo",
    createdAt: "2025-02-10T11:00:00",
    pets: [
      {
        id: "p4",
        clienteId: "4",
        nome: "Thor",
        raca: "Husky Siberiano",
        especie: "Cão",
        tamanho: "Grande",
        idade: "2 anos",
        peso: "28",
        observacoes: "",
        createdAt: "2025-02-10T11:30:00",
      },
    ],
  },
  {
    id: "5",
    nome: "Ana Costa",
    cpf: "567.890.123-44",
    telefonePrincipal: "(51) 95555-0005",
    telefoneSecundario: "",
    email: "ana.costa@email.com",
    cep: "90010-150",
    rua: "Av. Borges de Medeiros",
    numero: "100",
    complemento: "",
    bairro: "Centro Histórico",
    cidade: "Porto Alegre",
    estado: "RS",
    dataNascimento: "1988-09-30",
    comoConheceu: "Panfleto",
    observacoes: "",
    status: "Inativo",
    createdAt: "2025-02-20T14:00:00",
    pets: [],
  },
  {
    id: "6",
    nome: "Fernanda Rocha",
    cpf: "678.901.234-55",
    telefonePrincipal: "(11) 94444-0006",
    telefoneSecundario: "",
    email: "fernanda.rocha@email.com",
    cep: "04101-300",
    rua: "Rua Vergueiro",
    numero: "1500",
    complemento: "Casa",
    bairro: "Vila Mariana",
    cidade: "São Paulo",
    estado: "SP",
    dataNascimento: "1992-06-14",
    comoConheceu: "Instagram",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-03-01T09:30:00",
    pets: [],
  },
  {
    id: "7",
    nome: "Rafael Mendes",
    cpf: "789.012.345-66",
    telefonePrincipal: "(85) 93333-0007",
    telefoneSecundario: "",
    email: "rafael.mendes@email.com",
    cep: "60135-235",
    rua: "Av. Beira Mar",
    numero: "400",
    complemento: "",
    bairro: "Meireles",
    cidade: "Fortaleza",
    estado: "CE",
    dataNascimento: "1983-03-21",
    comoConheceu: "Redes sociais",
    observacoes: "Pet com problema cardíaco",
    status: "Ativo",
    createdAt: "2025-03-05T16:00:00",
    pets: [
      {
        id: "p5",
        clienteId: "7",
        nome: "Mel",
        raca: "Golden Retriever",
        especie: "Cão",
        tamanho: "Grande",
        idade: "4 anos",
        peso: "30",
        observacoes: "Acompanhamento cardíaco trimestral",
        createdAt: "2025-03-05T16:30:00",
      },
    ],
  },
  {
    id: "8",
    nome: "Patrícia Nunes",
    cpf: "890.123.456-77",
    telefonePrincipal: "(71) 92222-0008",
    telefoneSecundario: "",
    email: "patricia.nunes@email.com",
    cep: "40020-020",
    rua: "Av. Sete de Setembro",
    numero: "700",
    complemento: "",
    bairro: "Barra",
    cidade: "Salvador",
    estado: "BA",
    dataNascimento: "1997-12-01",
    comoConheceu: "Google",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-03-08T10:00:00",
    pets: [
      {
        id: "p6",
        clienteId: "8",
        nome: "Mingau",
        raca: "Siamês",
        especie: "Gato",
        tamanho: "Pequeno",
        idade: "2 anos",
        peso: "3.8",
        observacoes: "",
        createdAt: "2025-03-08T10:30:00",
      },
      {
        id: "p7",
        clienteId: "8",
        nome: "Pipoca",
        raca: "Coelho Anão",
        especie: "Coelho",
        tamanho: "Pequeno",
        idade: "1 ano",
        peso: "1.5",
        observacoes: "",
        createdAt: "2025-03-10T09:00:00",
      },
    ],
  },
  {
    id: "9",
    nome: "Gustavo Pires",
    cpf: "901.234.567-88",
    telefonePrincipal: "(62) 91111-0009",
    telefoneSecundario: "(62) 90000-0009",
    email: "gustavo.pires@email.com",
    cep: "74805-100",
    rua: "Rua 10",
    numero: "50",
    complemento: "",
    bairro: "Setor Bueno",
    cidade: "Goiânia",
    estado: "GO",
    dataNascimento: "1980-08-16",
    comoConheceu: "Indicação",
    observacoes: "",
    status: "Inativo",
    createdAt: "2025-03-10T13:00:00",
    pets: [],
  },
  {
    id: "10",
    nome: "Larissa Borges",
    cpf: "012.345.678-99",
    telefonePrincipal: "(11) 90000-0010",
    telefoneSecundario: "",
    email: "larissa.borges@email.com",
    cep: "01310-100",
    rua: "Av. Paulista",
    numero: "2000",
    complemento: "Cj 42",
    bairro: "Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    dataNascimento: "2000-01-25",
    comoConheceu: "TikTok",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-03-12T08:45:00",
    pets: [],
  },
  {
    id: "11",
    nome: "Bruno Carvalho",
    cpf: "111.222.333-00",
    telefonePrincipal: "(48) 99988-0011",
    telefoneSecundario: "",
    email: "bruno.carvalho@email.com",
    cep: "88010-970",
    rua: "Rua Felipe Schmidt",
    numero: "30",
    complemento: "",
    bairro: "Centro",
    cidade: "Florianópolis",
    estado: "SC",
    dataNascimento: "1987-05-09",
    comoConheceu: "Indicação",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-03-14T09:00:00",
    pets: [],
  },
  {
    id: "12",
    nome: "Camila Freitas",
    cpf: "222.333.444-11",
    telefonePrincipal: "(92) 98877-0012",
    telefoneSecundario: "",
    email: "camila.freitas@email.com",
    cep: "69010-060",
    rua: "Av. Eduardo Ribeiro",
    numero: "520",
    complemento: "",
    bairro: "Centro",
    cidade: "Manaus",
    estado: "AM",
    dataNascimento: "1993-10-17",
    comoConheceu: "Facebook",
    observacoes: "",
    status: "Ativo",
    createdAt: "2025-03-15T11:30:00",
    pets: [],
  },
];

export const useMockClientes = () =>
  useState<Cliente[]>("mock-clientes", () =>
    MOCK_CLIENTES.map((c) => ({ ...c })),
  );
