import type { Servico } from "~/types/servico";

export const useMockServicos = () =>
  useState<Servico[]>("servicos", () => [
    {
      id: "1",
      nome: "Banho",
      categoria: "higiene",
      porte: "pequeno",
      duracaoMin: 60,
      preco: 50,
      descricao: "Banho completo com secagem",
      ativo: true,
    },
    {
      id: "2",
      nome: "Banho",
      categoria: "higiene",
      porte: "medio",
      duracaoMin: 75,
      preco: 70,
      descricao: "Banho completo com secagem",
      ativo: true,
    },
    {
      id: "3",
      nome: "Banho",
      categoria: "higiene",
      porte: "grande",
      duracaoMin: 90,
      preco: 90,
      descricao: "Banho completo com secagem",
      ativo: true,
    },
    {
      id: "4",
      nome: "Tosa",
      categoria: "estetica",
      porte: "pequeno",
      duracaoMin: 60,
      preco: 60,
      ativo: true,
    },
    {
      id: "5",
      nome: "Tosa",
      categoria: "estetica",
      porte: "medio",
      duracaoMin: 75,
      preco: 80,
      ativo: true,
    },
    {
      id: "6",
      nome: "Tosa",
      categoria: "estetica",
      porte: "grande",
      duracaoMin: 90,
      preco: 110,
      ativo: true,
    },
    {
      id: "7",
      nome: "Banho e Tosa",
      categoria: "estetica",
      porte: "pequeno",
      duracaoMin: 90,
      preco: 100,
      ativo: true,
    },
    {
      id: "8",
      nome: "Banho e Tosa",
      categoria: "estetica",
      porte: "medio",
      duracaoMin: 120,
      preco: 130,
      ativo: true,
    },
    {
      id: "9",
      nome: "Banho e Tosa",
      categoria: "estetica",
      porte: "grande",
      duracaoMin: 150,
      preco: 170,
      ativo: true,
    },
    {
      id: "10",
      nome: "Consulta Veterinária",
      categoria: "saude",
      porte: "todos",
      duracaoMin: 30,
      preco: 150,
      descricao: "Consulta clínica geral",
      ativo: true,
    },
    {
      id: "11",
      nome: "Vacinação",
      categoria: "saude",
      porte: "todos",
      duracaoMin: 20,
      preco: 80,
      ativo: true,
    },
    {
      id: "12",
      nome: "Hospedagem (diária)",
      categoria: "hospedagem",
      porte: "todos",
      duracaoMin: 1440,
      preco: 80,
      descricao: "Hospedagem com alimentação inclusa",
      ativo: true,
    },
    {
      id: "13",
      nome: "Adestramento",
      categoria: "outros",
      porte: "todos",
      duracaoMin: 60,
      preco: 120,
      descricao: "Sessão de adestramento individual",
      ativo: false,
    },
  ]);
